#!/bin/sh
#
#-- remove old configuration files
#
rm -f depcomp missing install-sh mkinstalldirs libtool acconfig.h
rm -f configure Makefile.in config.status config.log config.guess config.cache 
rm -f aclocal.m4 ltmain.sh config.sub
rm -rf autom4te.cache Makefile Makefile.in *.lo
#
#-- end
